[[news]]
date = "2026-06"
content = "Our paper, “Integrative genomic and functional analysis of RAB3B in lung adenocarcinoma: associations with m6A modification and ceRNA networks,” was accepted by Frontiers in Pharmacology! (SCI Q1, IF 5.4) 🎉"

[[news]]
date = "2026-05"
content = "Our paper, “SQLE as a potential diagnostic and prognostic biomarker for LIHC: a multi-cohort and spatial study,” was accepted by npj Precision Oncology! (SCI Q1, IF 9.9) 🎉"

[[news]]
date = "2025-12"
content = "Our paper, “Integrated multi-omics and functional analysis uncovers the structural and regulatory significance of Nucleophosmin 1 in the metabolic progression of esophageal carcinoma,” was accepted by International Journal of Biological Macromolecules! (SCI Q1, IF 8.7) 🎉"

[[news]]
date = "2025-09"
content = "Started my Ph.D. studies at Soochow University."
